### ISSUE TITLE
[Tracker] Improvements and fixes to improve the demo

### ISSUE THREAD

**Issue by NathanLovato** [gdquest-demos/godot-4-3d-third-person-controller#11]
Higher priority:

- [ ] Make the character throw grenades in the character's look direction when not in aim mode
- [ ] Add dedicated sound effects
  + Beefy bullet sound
  + Grenade throw
  + Grenade explosion
  + Impact sounds on enemies
  + Impact sounds on other materials
  + Enemy death (special impact sound, as in e.g. Zelda BoTW?)
  + Cloud puff (enemy death particles)
  + Player step sounds
    + Soil
    + Grass
    + Metal (for jump pads)
  + Player jump
  + Player land
- [ ] Add a more fitting audio soundtrack
- [ ] Limit the rate of shooting (both grenade and rifle)
- [ ] Make shooting with the rifle continuous when holding the left mouse button down
- [ ] Bug: The jump pad does not always work

Lower priority:

- [ ] The punch attack would benefit from having two animations
- [ ] Add an aiming animation and make the character aim their arm where they're looking
- [ ] Add a reticle when aiming with the gun
- [ ] The coins should have an easing when moving to the character

**Comment by GigglingGalaxy** [comment]
Known Bugs 
Beetle: Add a NavigationAgent3d Node to Beetle, 
change Beetle code line 37 to set_target_position and line 39 to get_next_path_position. 
DemoPage: tween.tween_property(demo_page_root, "modulate", Color.WHITE, 0.3) change white to BLACK or you can't see controls (or just change "blur" in tree color to 000000a9 or something closer to black). 
Player: have to # out all "punch" code references because they don't work. # _character_skin.punch() 
PlayerSkin: #func punch(): #animation_tree["parameters/PunchOneShot/active"] = true Shaders Error: even after reimport/tool: E 0:00:00:0527 SCREEN_TEXTURE has been removed in favor of using hint_screen_texture with a uniform. To continue with minimal code changes add 'uniform sampler2D SCREEN_TEXTURE : hint_screen_texture, filter_linear_mipmap;' near the top of your shader. <C++ Source> :7 ^has to do with the voronoi at top of shader on smoke_ball shader. It still works even with error though. These lines: uniform sampler2D voronoi_sampler; varying float voronoi; replace as error says, then varying float error occurs.

**Comment by NathanLovato** [comment]
Thanks for taking the time to list these! In general, I think the project may need to be ported to Godot 4.2 or 4.3. Nothing should be commented out, just properly ported if anything stopped working with the latest Godot release.

We won't have time to do this ourselves soon, but contributions are welcome if anyone wants to tackle this.
